#!/usr/bin/env python3
"""Create or update Windrose's ServerDescription.json safely.

Blank INVITE_CODE and WORLD_ISLAND_ID variables deliberately preserve values
already generated by Windrose. Non-empty variables are explicit administrator
overrides, which is useful when importing an existing world or invite code.
"""

from __future__ import annotations

import json
import os
import re
import sys
import tempfile
import uuid
from pathlib import Path
from typing import Any

TRUTHY_VALUES = {"1", "true", "yes", "on"}
FALSY_VALUES = {"0", "false", "no", "off"}
PERSISTENT_ID_PATTERN = re.compile(r"^[0-9A-F]{32}$")


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None or value.strip() == "":
        return default
    normalized = value.strip().lower()
    if normalized in TRUTHY_VALUES:
        return True
    if normalized in FALSY_VALUES:
        return False
    raise ValueError(f"{name} must be a boolean, got: {value!r}")


def env_int(name: str, default: int, minimum: int, maximum: int) -> int:
    value = os.getenv(name)
    if value is None or value.strip() == "":
        return default
    try:
        parsed = int(value)
    except ValueError as exc:
        raise ValueError(f"{name} must be an integer, got: {value!r}") from exc
    if not minimum <= parsed <= maximum:
        raise ValueError(f"{name} must be between {minimum} and {maximum}, got: {parsed}")
    return parsed


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists() or path.stat().st_size == 0:
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Refusing to overwrite invalid JSON in {path}: line {exc.lineno}, column {exc.colno}"
        ) from exc
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object in {path}")
    return value


def detected_deployment_id(server_root: Path) -> str:
    override = os.getenv("WINDROSE_DEPLOYMENT_ID", "").strip()
    if override:
        return override
    marker = server_root / ".windrose-deployment-id"
    if marker.is_file():
        return marker.read_text(encoding="utf-8").strip()
    return ""


def atomic_write(path: Path, config: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(config, handle, indent=4, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def configure() -> Path:
    server_root = Path(os.getenv("WINDROSE_SERVER_ROOT", "/home/container"))
    config_path = Path(
        os.getenv("WINDROSE_CONFIG_PATH", str(server_root / "R5/ServerDescription.json"))
    )
    config = load_config(config_path)

    config.setdefault("Version", 1)
    deployment_id = detected_deployment_id(server_root)
    if not str(config.get("DeploymentId", "")).strip() and deployment_id:
        config["DeploymentId"] = deployment_id

    persistent = config.setdefault("ServerDescription_Persistent", {})
    if not isinstance(persistent, dict):
        raise ValueError("ServerDescription_Persistent must be a JSON object")

    persistent_id = str(persistent.get("PersistentServerId", "")).strip().upper()
    if not PERSISTENT_ID_PATTERN.fullmatch(persistent_id):
        persistent_id = uuid.uuid4().hex.upper()
    persistent["PersistentServerId"] = persistent_id

    invite_code = os.getenv("INVITE_CODE", "").strip()
    if invite_code:
        persistent["InviteCode"] = invite_code
    else:
        persistent.setdefault("InviteCode", "")

    password = os.getenv("PASSWORD", "")
    persistent["IsPasswordProtected"] = bool(password)
    persistent["Password"] = password

    server_name = os.getenv("SERVER_NAME")
    if server_name is not None:
        persistent["ServerName"] = server_name
    else:
        persistent.setdefault("ServerName", "Pterodactyl Windrose Server")

    world_island_id = os.getenv("WORLD_ISLAND_ID", "").strip()
    if world_island_id:
        persistent["WorldIslandId"] = world_island_id
    else:
        persistent.setdefault("WorldIslandId", "")

    persistent["MaxPlayerCount"] = env_int("MAX_PLAYER_COUNT", 8, 1, 10)
    persistent["UserSelectedRegion"] = os.getenv("USER_SELECTED_REGION", "EU").strip()
    persistent["P2pProxyAddress"] = os.getenv("P2P_PROXY_ADDRESS", "127.0.0.1").strip()
    persistent["UseDirectConnection"] = env_bool("USE_DIRECT_CONNECTION", False)
    persistent["DirectConnectionServerAddress"] = os.getenv(
        "DIRECT_CONNECTION_SERVER_ADDRESS", ""
    ).strip()
    persistent["DirectConnectionServerPort"] = env_int(
        "DIRECT_CONNECTION_SERVER_PORT",
        int(os.getenv("SERVER_PORT", "7777")),
        1,
        65535,
    )
    persistent["DirectConnectionProxyAddress"] = os.getenv(
        "DIRECT_CONNECTION_PROXY_ADDRESS", "0.0.0.0"
    ).strip()
    persistent["AutoLoadLatestBackupIfHasBroken"] = env_bool(
        "AUTO_LOAD_LATEST_BACKUP_IF_HAS_BROKEN", True
    )
    persistent["CanLaunchMultipleServerInstances"] = False

    atomic_write(config_path, config)
    return config_path


def main() -> int:
    try:
        path = configure()
    except (OSError, ValueError) as exc:
        print(f"Windrose configuration failed: {exc}", file=sys.stderr)
        return 1
    print(f"Windrose configuration updated: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
